//
//  Study.m
//  NaturalizeME
//
//  Created by James Carlson on 7/16/15.
//  Copyright (c) 2015 JC2 Dev. All rights reserved.
//

#import "Study.h"

static NSString *const QuestionNumberKey = @"questionNumber";
static NSString *const QuestionTitleKey = @"questionTitle";
static NSString *const AnswerKey = @"answer";
static NSString *const AnswersKey = @"answers";
static NSString *const AnswersNeededKey = @"answersNeeded";
static NSString *const BadAnswerKey = @"badAnswer";
static NSString *const ExplanationKey = @"explanationTitle";

@implementation Study

+(NSInteger)questionCount {
    return [[self answers]count];
}

+(NSDictionary *)questionAtIndex:(NSInteger)index {
    return [self answers][index];
}

+(NSString *)questionNumberAtIndex:(NSInteger)index {
    return [self answers][index][QuestionNumberKey];
}

+(NSString *)questionTitleAtIndex:(NSInteger)index {
    return [self answers][index][QuestionTitleKey];
}

+(NSNumber *)answersNeededAtIndex:(NSInteger)index {
    return [self answers][index][AnswersNeededKey];
}

+(NSInteger)answerCountAtIndex:(NSInteger)index {
    return [[self answers][index][AnswerKey]count];
}

+(NSString *)answerAtIndex:(NSInteger)ingIndex inQuestionAtIndex:(NSInteger)ansIndex {
    return [self answers][ansIndex][AnswerKey][ingIndex][AnswersKey];
}

+(NSString *)explanationAtIndex:(NSInteger)index {
    return [self answers][index][ExplanationKey];
}


+(NSArray *)answers {
    
    return @[
             @{QuestionNumberKey: @"1",
               QuestionTitleKey: @"What is the supreme law of the land?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"The Constitution"}],
               ExplanationKey: @"The constitution is the supreme law of the land"
               },
             @{QuestionNumberKey: @"2",
               QuestionTitleKey: @"What does the Constitution do?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Establishes the Government"},
                             @{AnswersKey: @"Defines the Government"},
                             @{AnswersKey: @"Protect the basic rights of the people"},
                             @{BadAnswerKey: @"Protect the rights of the Government over the people"},
                             @{BadAnswerKey: @"Declared our Freedom"},
                             @{BadAnswerKey: @"Established borders for the 50 states"},
                             @{BadAnswerKey: @"Said who the 1st President will be"},
                             @{BadAnswerKey: @"Declares who will be in the Supreme Court"},
                             @{BadAnswerKey: @"Says who the next President will be"}],
               ExplanationKey: @"The Constitution of the United States divides government power between the national government and state governments. The name for this division of power is “federalism.” Federalism is an important idea in the Constitution. We call the Founding Fathers who wrote the Constitution the “Framers” of the Constitution. The Framers wanted to limit the powers of the government, so they separated the powers into three branches: executive, legislative, and judicial. The Constitution explains the power of each branch. The Constitution also includes changes and additions, called “amendments.” The first 10 amendments are called the “Bill of Rights.” The Bill of Rights established the individual rights and liberties of all Americans."
               },
             @{QuestionNumberKey: @"3",
               QuestionTitleKey: @"The idea of self-government is in the first three words of the Constitution. What are these words?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"We the People"}],
               ExplanationKey: @"We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America."
               },
             @{QuestionNumberKey: @"4",
               QuestionTitleKey: @"What is an amendment?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"A change (to the Constitution)"},
                             @{AnswersKey: @"An addition (to the Constitution)"},
                             @{BadAnswerKey: @"A person"},
                             @{BadAnswerKey: @"A position in the government"},
                             @{BadAnswerKey: @"An example (for writing the Constitution)"},
                             @{BadAnswerKey: @"A copy (of the Constitution)"},
                             @{BadAnswerKey: @"Another country's Constitution"}],
               ExplanationKey: @"An amendment is a change or addition to the Constitution. The Framers of the Constitution knew that laws can change as a country grows. They did not want to make it too easy to modify the Constitution, the supreme law of the land. The Framers also did not want the Constitution to lose its meaning. For this reason, the Framers decided that Congress could pass amendments in only two ways: by a two-thirds vote in the U.S. Senate and the House of Representatives or by a special convention. A special convention has to be requested by two-thirds of the states. After an amendment has passed in Congress or by a special convention, the amendment must then be ratified (accepted) by the legislatures of three-fourths of the states. The amendment can also be ratified by a special convention in three-fourths of the states. Not all proposed amendments are ratified. Six times in U.S. history amendments have passed in Congress but were not approved by enough states to be ratified."
               },
             @{QuestionNumberKey: @"5",
               QuestionTitleKey: @"What do we call the first ten amendments to the Constitution?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"The Bill of Rights"}],
               ExplanationKey: @"The Bill of Rights is the first 10 amendments to the Constitution. When the Framers wrote the Constitution, they did not focus on individual rights.They focused on creating the system and structure of government. Many Americans believed that the Constitution should guarantee the rights of the people, and they wanted a list of all the things a government could not do."
               },
             @{QuestionNumberKey: @"6",
               QuestionTitleKey: @"What is one right or freedom from the First Amendment?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Speech"},
                             @{AnswersKey: @"Religion"},
                             @{AnswersKey: @"Assembly"},
                             @{AnswersKey: @"Press"},
                             @{AnswersKey: @"Petition the government"},
                             @{BadAnswerKey: @"Power"},
                             @{BadAnswerKey: @"Refusal"},
                             @{BadAnswerKey: @"Bear Arms"},
                             @{BadAnswerKey: @"Serve in the Government"},
                             @{BadAnswerKey: @"Business"}],
               ExplanationKey: @"The First Amendment of the Bill of Rights protects a person’s right to freedom of expression. Freedom of expression allows open discussion and debate on public issues. Open discussion and debate are important to democracy. The First Amendment also protects freedom of religion and free speech. This amendment says that Congress may not pass laws that establish an official religion and may not limit religious expression. Congress may not pass laws that limit freedom of the press or the right of people to meet peacefully. The First Amendment also gives people the right to petition the government to change laws or acts that are not fair. Congress may not take away these rights. The First Amendment of the Constitution guarantees and protects these rights."
               },
             @{QuestionNumberKey: @"7",
               QuestionTitleKey: @"How many amendments does the Constitution have?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Twenty seven"},
                             @{BadAnswerKey: @"Thirty two"},
                             @{BadAnswerKey: @"Twenty six"},
                             @{BadAnswerKey: @"Twenty eight"},
                             @{BadAnswerKey: @"Fifteen"},
                             @{BadAnswerKey: @"Thirteen"}],
               ExplanationKey: @"The first 10 amendments to the Constitution are called the Bill of Rights. They were added in 1791. Since then, 17 more amendments have been added. The Constitution currently has 27 amendments. The 27th Amendment was added in 1992. It explains how senators and representatives are paid. Interestingly, Congress first discussed this amendment back in 1789 as one of the original amendments considered for the Bill of Rights."
               },
             @{QuestionNumberKey: @"8",
               QuestionTitleKey: @"What did the Declaration of Independence do?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Announced our independence (from Great Britain)"},
                             @{AnswersKey: @"Declared our independence (from Great Britain)"},
                             @{BadAnswerKey: @"Establish the Government (like Great Brtitain)"},
                             @{BadAnswerKey: @"Allows us to buy fireworks"},
                             @{BadAnswerKey: @"Established basic right of US citizens"},
                             @{BadAnswerKey: @"Created fifty states"},
                             @{BadAnswerKey: @"Brought Christopher Columbus to the US"}],
               ExplanationKey: @"The Declaration of Independence contains important ideas about the American system of government. The Declaration of Independence states that all people are created equal and have “certain unalienable rights.” These are rights that no government can change or take away. The author of the Declaration, Thomas Jefferson, wrote that the American colonies should be independent because Great Britain did not respect the basic rights of people in the colonies. Jefferson believed that a government exists only if the people think it should. He believed in the idea that the people create their own government and consent, or agree, to follow laws their government makes."
               },
             @{QuestionNumberKey: @"9",
               QuestionTitleKey: @"What are two rights in the Declaration of Independence?",
               AnswersNeededKey: @2,
               AnswerKey : @[@{AnswersKey: @"Life"},
                             @{AnswersKey: @"Liberty"},
                             @{AnswersKey: @"Pursuit of happiness"},
                             @{BadAnswerKey: @"Carry Guns"},
                             @{BadAnswerKey: @"Create a business"},
                             @{BadAnswerKey: @"Vote"},
                             @{BadAnswerKey: @"Own land"},
                             @{BadAnswerKey: @"Travel freely between states"}],
               ExplanationKey: @"The Declaration of Independence lists three rights that the Founding Fathers considered to be natural and “unalienable.” They are the right to life, liberty, and the pursuit of happiness. These ideas about freedom and individual rights were the basis for declaring America’s independence. Thomas Jefferson and the other Founding Fathers believed that people are born with natural rights that no government can take away. Government exists to protect these rights. Because the people voluntarily give up power to a government, they can take that power back. The British government was not protecting the rights of the colonists, so the colonies took back their power and separated from Great Britain."
               },
             @{QuestionNumberKey: @"10",
               QuestionTitleKey: @"What is freedom of religion?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"You can practice any religion"},
                             @{AnswersKey: @"You can choose to not practice a religion"},
                             @{BadAnswerKey: @"You can force people to pray"},
                             @{BadAnswerKey: @"You can prevent people from praying"},
                             @{BadAnswerKey: @"You can carry a gun"},
                             @{BadAnswerKey: @"You can become rich"},
                             @{BadAnswerKey: @"You can become famous"}],
               ExplanationKey: @"Colonists from Spain, France, Holland, England, and other countries came to America for many different reasons. One of the reasons was religious freedom. The rulers of many of these countries told their citizens that they must go to a certain church and worship in a certain way. Some people had different religious beliefs than their rulers and wanted to have their own churches. In 1620, the Pilgrims were the first group that came to America seeking religious freedom. Religious freedom was also important to the Framers. For this reason, freedom of religion was included in the Constitution as part of the Bill of Rights. The First Amendment to the Constitution guarantees freedom of religion. The First Amendment states, “Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof.” The First Amendment also prohibits Congress from setting up an official U.S. religion, and protects citizens’ rights to hold any religious belief, or none at all."
               },
             @{QuestionNumberKey: @"11",
               QuestionTitleKey: @"What is the economic system in the United States?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Capitalist economy"},
                             @{AnswersKey: @"Market economy"},
                             @{BadAnswerKey: @"Communist economy"},
                             @{BadAnswerKey: @"Democratic economy"},
                             @{BadAnswerKey: @"Republican economy"},
                             @{BadAnswerKey: @"Independent economy"},
                             @{BadAnswerKey: @"Money market"}],
               ExplanationKey: @"The economic system of the United States is capitalism. In the American economy, most businesses are privately owned. Competition and profit motivate businesses. Businesses and consumers interact in the marketplace, where prices can be negotiated."
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"What is the “rule of law”?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Everyone must follow the law"},
                             @{AnswersKey: @"The Government must obey the law"},
                             @{AnswersKey: @"No one is above the law"},
                             @{AnswersKey: @"Leaders must obey the law"},
                             @{BadAnswerKey: @"The Government does not need to obey the law"},
                             @{BadAnswerKey: @"The rich can make the laws"},
                             @{BadAnswerKey: @"Politicians are exempt from the law"},
                             @{BadAnswerKey: @"The law will expire every thirty five years"},
                             @{BadAnswerKey: @"Everyone must read about the law"}],
               ExplanationKey: @"John Adams was one of the Founding Fathers and the second president of the United States. He wrote that our country is, “a government of laws, and not of men.” No person or group is above the law. The rule of law means that everyone (citizens and leaders) must obey the laws. In the United States, the U.S. Constitution is the foundation for the rule of law. The United States is a “constitutional democracy” (a democracy with a constitution). In constitutional democracies, people are willing to obey the laws because the laws are made by the people through their elected representatives. If all people are governed by the same laws, the individual rights and liberties of each person are better protected. The rule of law helps to make sure that government protects all people equally and does not violate the rights of certain people."
               },
             @{QuestionNumberKey: @"13",
               QuestionTitleKey: @"Name one branch or part of the government.",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Congress"},
                             @{AnswersKey: @"Legislative"},
                             @{AnswersKey: @"President"},
                             @{AnswersKey: @"Executive"},
                             @{AnswersKey: @"The Courts"},
                             @{AnswersKey: @"Judicial"},
                             @{BadAnswerKey: @"Democratic"},
                             @{BadAnswerKey: @"Republican"},
                             @{BadAnswerKey: @"Independent"},
                             @{BadAnswerKey: @"Incumbent"},
                             @{BadAnswerKey: @"The State"}],
               ExplanationKey: @"The Constitution establishes three branches of government: legislative, executive, and judicial. Article I of the Constitution establishes the legislative branch. Article I explains that Congress makes laws. Congress (the Senate and the House of Representatives) is the legislative branch of the U.S. government. Article II of the Constitution establishes the executive branch."
               },
             @{QuestionNumberKey: @"14",
               QuestionTitleKey: @"What stops one branch of government from becoming too powerful?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Checks and Balances"},
                             @{AnswersKey: @"Separation of the powers"},
                             @{BadAnswerKey: @"The Declaration of Independence"},
                             @{BadAnswerKey: @"The individual States"},
                             @{BadAnswerKey: @"The Vice President"},
                             @{BadAnswerKey: @"Voting"},
                             @{BadAnswerKey: @"Separation of the classes"}],
               ExplanationKey: @"The Constitution separates the government’s power into three branches to prevent one person or group from having too much power. The separation of government into three branches creates a system of checks and balances. This means that each branch can block, or threaten to block, the actions of the other branches. Here are some examples: the Senate (part of the legislative branch) can block a treaty signed by the president (the executive branch). In this example, the legislative branch is “checking” the executive. The U.S. Supreme Court (the judicial branch) can reject a law passed by Congress (the legislative branch). In this example, the judicial branch is “checking” the legislative branch. This separation of powers limits the power of the government and prevents the government from violating the rights of the people."
               },
             @{QuestionNumberKey: @"15",
               QuestionTitleKey: @"Who is in charge of the executive branch?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"The President"},
                             @{BadAnswerKey: @"The Vice President"},
                             @{BadAnswerKey: @"The Speaker of the House"},
                             @{BadAnswerKey: @"The Democratic Majority Leader"},
                             @{BadAnswerKey: @"The Republican Majority Leader"},
                             @{BadAnswerKey: @"The Department of State"}],
               ExplanationKey: @"The job of the executive branch is to carry out, or execute, federal laws and enforce laws passed by Congress. The head of the executive branch is the president. The president is both the head of state and the head of government. The president’s powers include the ability to sign treaties with other countries and to select ambassadors to represent the United States around the world. The president also sets national policies and proposes laws to Congress. The president names the top leaders of the federal departments."
               },
             @{QuestionNumberKey: @"16",
               QuestionTitleKey: @"Who makes federal laws?",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @"Congress"},
                             @{AnswersKey: @"The Senate and House (of Representatives)"},
                             @{AnswersKey: @"US/National legislature"},
                             @{BadAnswerKey: @"The Supreme Court"},
                             @{BadAnswerKey: @"States"},
                             @{BadAnswerKey: @"The FBI"},
                             @{BadAnswerKey: @"The Declaration of Independence"},
                             @{BadAnswerKey: @"The Emancipation Proclamation"}],
               ExplanationKey: @"Congress makes federal laws. A federal law usually applies to all states and all people in the United States. Either side of Congress—the Senate or the House of Representatives—can propose a bill to address an issue. When the Senate proposes a bill, it sends the bill to a Senate committee. The Senate committee studies the issue and the bill. When the House of Representatives proposes a bill, it sends the bill to a House of Representatives committee. The committee studies the bill and sometimes makes changes to it. Then the bill goes to the full House or Senate for consideration. When each chamber passes its own version of the bill, it often goes to a “conference committee.” The conference committee has members from both the House and the Senate. This committee discusses the bill, tries to resolve the differences, and writes a report with the final version of the bill. Then the committee sends the final version of the bill back to both houses for approval. If both houses approve the bill, it is considered “enrolled.” An enrolled bill goes to the president to be signed into law. If the president signs the bill, it becomes a federal law."
               },
             @{QuestionNumberKey: @"17",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@{AnswersKey: @""},
                             @{AnswersKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""},
                             @{BadAnswerKey: @""}],
               ExplanationKey: @""
               },
             
             ];
}

-(void)holderArray {
    self.holder = [[NSMutableArray alloc]initWithObjects:@0,@1,@2,@3,@4,@5,@6,@7,@8,@9,@10,@11,@12,@13,@14,@15,@16,@17,@18,@19,@20,@21,@22,@23,@24,@25,@26,@27,@28,@29,@30,@31,@32,@33,@34,@35,@36,@37,@38,@39,@40,@41,@42,@43,@44,@45,@46,@47,@48,@49,@50,@51,@52,@53,@54,@55,@56,@57,@58,@59,@60,@61,@62,@63,@64,@65,@66,@67,@68,@69,@70,@71,@72,@73,@74,@75,@76,@77,@78,@79,@80,@81,@82,@83,@84,@85,@86,@87,@88,@89,@90,@91,@92,@93,@94,@95,@96,@97,@98,@99,nil];
}


@end
