//
//  Study.m
//  NaturalizeME
//
//  Created by James Carlson on 7/16/15.
//  Copyright (c) 2015 JC2 Dev. All rights reserved.
//

#import "Study.h"

static NSString *const QuestionNumberKey = @"questionNumber";
static NSString *const QuestionTitleKey = @"questionTitle";
static NSString *const AnswerKey = @"answer";
static NSString *const AnswersKey = @"answers";
static NSString *const AnswersNeededKey = @"answersNeeded";
static NSString *const BadAnswerKey = @"badAnswer";
static NSString *const ExplanationKey = @"explanationTitle";

@implementation Study

+(NSInteger)questionCount {
    return [[self answers]count];
}

+(NSDictionary *)questionAtIndex:(NSInteger)index {
    return [self answers][index];
}

+(NSString *)questionNumberAtIndex:(NSInteger)index {
    return [self answers][index][QuestionNumberKey];
}

+(NSString *)questionTitleAtIndex:(NSInteger)index {
    return [self answers][index][QuestionTitleKey];
}

+(NSNumber *)answersNeededAtIndex:(NSInteger)index {
    return [self answers][index][AnswersNeededKey];
}

+(NSInteger)answerCountAtIndex:(NSInteger)index {
    return [[self answers][index][AnswerKey]count];
}

+(NSString *)answerAtIndex:(NSInteger)ingIndex inQuestionAtIndex:(NSInteger)ansIndex {
    return [self answers][ansIndex][AnswerKey][ingIndex];
}

+(NSString *)BadAnswerAtIndex:(NSInteger)ingIndex inQuestionAtIndex:(NSInteger)ansIndex {
    return [self answers][ansIndex][BadAnswerKey][ingIndex];
}

+(NSString *)explanationAtIndex:(NSInteger)index {
    return [self answers][index][ExplanationKey];
}


+(NSArray *)answers {
    
    return @[
             @{QuestionNumberKey: @"1",
               QuestionTitleKey: @"What is the supreme law of the land?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"The Constitution"],
               BadAnswerKey: @[@"The Golden Rule",
                               @"The State Laws",
                               @"The The Declaration Of Independence",
                               @"The word of the President",
                               @"The vote of a citizen",
                               @"The final round in Jeopardy"],
               ExplanationKey: @"The constitution is the supreme law of the land"
               },
             @{QuestionNumberKey: @"2",
               QuestionTitleKey: @"What does the Constitution do?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Establishes the Government",
                             @"Defines the Government",
                             @"Protect the basic rights of the people"],
               BadAnswerKey: @[@"Protect the rights of the Government over the people",
                               @"Declared our Freedom",
                               @"Established borders for the 50 states",
                               @"Said who the 1st President will be",
                               @"Declares who will be in the Supreme Court",
                               @"Says who the next President will be"],
               ExplanationKey: @"The Constitution of the United States divides government power between the national government and state governments. The name for this division of power is “federalism.” Federalism is an important idea in the Constitution. We call the Founding Fathers who wrote the Constitution the “Framers” of the Constitution. The Framers wanted to limit the powers of the government, so they separated the powers into three branches: executive, legislative, and judicial. The Constitution explains the power of each branch. The Constitution also includes changes and additions, called “amendments.” The first 10 amendments are called the “Bill of Rights.” The Bill of Rights established the individual rights and liberties of all Americans."
               },
             @{QuestionNumberKey: @"3",
               QuestionTitleKey: @"The idea of self-government is in the first three words of the Constitution. What are these words?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"We the People"],
               BadAnswerKey: @[@"Four score and",
                               @"I pledge allegiance",
                               @"Live long and",
                               @"Protect and serve",
                               @"When, in the",
                               @"We hold these"],
               ExplanationKey: @"We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America."
               },
             @{QuestionNumberKey: @"4",
               QuestionTitleKey: @"What is an amendment?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"A change (to the Constitution)",
                             @"An addition (to the Constitution)"],
               BadAnswerKey: @[@"A person",
                               @"A position in the government",
                               @"An example (for writing the Constitution)",
                               @"A copy (of the Constitution)",
                               @"Another country's Constitution"],
               ExplanationKey: @"An amendment is a change or addition to the Constitution. The Framers of the Constitution knew that laws can change as a country grows. They did not want to make it too easy to modify the Constitution, the supreme law of the land. The Framers also did not want the Constitution to lose its meaning. For this reason, the Framers decided that Congress could pass amendments in only two ways: by a two-thirds vote in the U.S. Senate and the House of Representatives or by a special convention. A special convention has to be requested by two-thirds of the states. After an amendment has passed in Congress or by a special convention, the amendment must then be ratified (accepted) by the legislatures of three-fourths of the states. The amendment can also be ratified by a special convention in three-fourths of the states. Not all proposed amendments are ratified. Six times in U.S. history amendments have passed in Congress but were not approved by enough states to be ratified."
               },
             @{QuestionNumberKey: @"5",
               QuestionTitleKey: @"What do we call the first ten amendments to the Constitution?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"The Bill of Rights"],
               BadAnswerKey: @[@"The laws of the people",
                               @"The Right of the Declaration Of Independence",
                               @"The Magna Carta",
                               @"The Bill of Inclusion",
                               @"The Bill of Exclusion"],
               ExplanationKey: @"The Bill of Rights is the first 10 amendments to the Constitution. When the Framers wrote the Constitution, they did not focus on individual rights.They focused on creating the system and structure of government. Many Americans believed that the Constitution should guarantee the rights of the people, and they wanted a list of all the things a government could not do."
               },
             @{QuestionNumberKey: @"6",
               QuestionTitleKey: @"What is one right or freedom from the First Amendment?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Speech",
                             @"Religion",
                             @"Assembly",
                             @"Press",
                             @"Petition the government"],
               BadAnswerKey: @[@"Power",
                               @"Refusal",
                               @"Bear Arms",
                               @"Serve in the Government",
                               @"Business"],
               ExplanationKey: @"The First Amendment of the Bill of Rights protects a person’s right to freedom of expression. Freedom of expression allows open discussion and debate on public issues. Open discussion and debate are important to democracy. The First Amendment also protects freedom of religion and free speech. This amendment says that Congress may not pass laws that establish an official religion and may not limit religious expression. Congress may not pass laws that limit freedom of the press or the right of people to meet peacefully. The First Amendment also gives people the right to petition the government to change laws or acts that are not fair. Congress may not take away these rights. The First Amendment of the Constitution guarantees and protects these rights."
               },
             @{QuestionNumberKey: @"7",
               QuestionTitleKey: @"How many amendments does the Constitution have?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Twenty seven"],
               BadAnswerKey: @[@"Thirty two",
                               @"Twenty six",
                               @"Twenty eight",
                               @"Fifteen",
                               @"Thirteen"],
               ExplanationKey: @"The first 10 amendments to the Constitution are called the Bill of Rights. They were added in 1791. Since then, 17 more amendments have been added. The Constitution currently has 27 amendments. The 27th Amendment was added in 1992. It explains how senators and representatives are paid. Interestingly, Congress first discussed this amendment back in 1789 as one of the original amendments considered for the Bill of Rights."
               },
             @{QuestionNumberKey: @"8",
               QuestionTitleKey: @"What did the Declaration of Independence do?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Announced our independence (from Great Britain)",
                             @"Declared our independence (from Great Britain)"],
               BadAnswerKey: @[@"Establish the Government (like Great Brtitain)",
                               @"Allows us to buy fireworks",
                               @"Established basic right of US citizens",
                               @"Created fifty states",
                               @"Brought Christopher Columbus to the US"],
               ExplanationKey: @"The Declaration of Independence contains important ideas about the American system of government. The Declaration of Independence states that all people are created equal and have “certain unalienable rights.” These are rights that no government can change or take away. The author of the Declaration, Thomas Jefferson, wrote that the American colonies should be independent because Great Britain did not respect the basic rights of people in the colonies. Jefferson believed that a government exists only if the people think it should. He believed in the idea that the people create their own government and consent, or agree, to follow laws their government makes."
               },
             @{QuestionNumberKey: @"9",
               QuestionTitleKey: @"What are two rights in the Declaration of Independence?",
               AnswersNeededKey: @2,
               AnswerKey : @[@"Life",
                             @"Liberty",
                             @"Pursuit of happiness"],
               BadAnswerKey: @[@"Carry Guns",
                               @"Create a business",
                               @"Vote",
                               @"Own land",
                               @"Travel freely between states"],
               ExplanationKey: @"The Declaration of Independence lists three rights that the Founding Fathers considered to be natural and “unalienable.” They are the right to life, liberty, and the pursuit of happiness. These ideas about freedom and individual rights were the basis for declaring America’s independence. Thomas Jefferson and the other Founding Fathers believed that people are born with natural rights that no government can take away. Government exists to protect these rights. Because the people voluntarily give up power to a government, they can take that power back. The British government was not protecting the rights of the colonists, so the colonies took back their power and separated from Great Britain."
               },
             @{QuestionNumberKey: @"10",
               QuestionTitleKey: @"What is freedom of religion?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"You can practice any religion",
                             @"You can choose to not practice a religion"],
                             BadAnswerKey: @[@"You can force people to pray",
                             @"You can prevent people from praying",
                             @"You can carry a gun",
                             @"You can become rich",
                             @"You can become famous"],
               ExplanationKey: @"Colonists from Spain, France, Holland, England, and other countries came to America for many different reasons. One of the reasons was religious freedom. The rulers of many of these countries told their citizens that they must go to a certain church and worship in a certain way. Some people had different religious beliefs than their rulers and wanted to have their own churches. In 1620, the Pilgrims were the first group that came to America seeking religious freedom. Religious freedom was also important to the Framers. For this reason, freedom of religion was included in the Constitution as part of the Bill of Rights. The First Amendment to the Constitution guarantees freedom of religion. The First Amendment states, “Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof.” The First Amendment also prohibits Congress from setting up an official U.S. religion, and protects citizens’ rights to hold any religious belief, or none at all."
               },
             @{QuestionNumberKey: @"11",
               QuestionTitleKey: @"What is the economic system in the United States?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Capitalist economy",
                             @"Market economy"],
                             BadAnswerKey: @[@"Communist economy",
                             @"Democratic economy",
                             @"Republican economy",
                             @"Independent economy",
                             @"Money market"],
               ExplanationKey: @"The economic system of the United States is capitalism. In the American economy, most businesses are privately owned. Competition and profit motivate businesses. Businesses and consumers interact in the marketplace, where prices can be negotiated."
               },
             @{QuestionNumberKey: @"12",
               QuestionTitleKey: @"What is the “rule of law”?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Everyone must follow the law",
                             @"The Government must obey the law",
                             @"No one is above the law",
                             @"Leaders must obey the law"],
                             BadAnswerKey: @[@"The Government does not need to obey the law",
                             @"The rich can make the laws",
                             @"Politicians are exempt from the law",
                             @"The law will expire every thirty five years",
                             @"Everyone must read about the law"],
               ExplanationKey: @"John Adams was one of the Founding Fathers and the second president of the United States. He wrote that our country is, “a government of laws, and not of men.” No person or group is above the law. The rule of law means that everyone (citizens and leaders) must obey the laws. In the United States, the U.S. Constitution is the foundation for the rule of law. The United States is a “constitutional democracy” (a democracy with a constitution). In constitutional democracies, people are willing to obey the laws because the laws are made by the people through their elected representatives. If all people are governed by the same laws, the individual rights and liberties of each person are better protected. The rule of law helps to make sure that government protects all people equally and does not violate the rights of certain people."
               },
             @{QuestionNumberKey: @"13",
               QuestionTitleKey: @"Name one branch or part of the government.",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Congress",
                             @"Legislative",
                             @"President",
                             @"Executive",
                             @"The Courts",
                             @"Judicial"],
                             BadAnswerKey: @[@"Democratic",
                             @"Republican",
                             @"Independent",
                             @"Incumbent",
                             @"The State"],
               ExplanationKey: @"The Constitution establishes three branches of government: legislative, executive, and judicial. Article I of the Constitution establishes the legislative branch. Article I explains that Congress makes laws. Congress (the Senate and the House of Representatives) is the legislative branch of the U.S. government. Article II of the Constitution establishes the executive branch."
               },
             @{QuestionNumberKey: @"14",
               QuestionTitleKey: @"What stops one branch of government from becoming too powerful?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Checks and Balances",
                             @"Separation of the powers"],
                             BadAnswerKey: @[@"The Declaration of Independence",
                             @"The individual States",
                             @"The Vice President",
                             @"Voting",
                             @"Separation of the classes"],
               ExplanationKey: @"The Constitution separates the government’s power into three branches to prevent one person or group from having too much power. The separation of government into three branches creates a system of checks and balances. This means that each branch can block, or threaten to block, the actions of the other branches. Here are some examples: the Senate (part of the legislative branch) can block a treaty signed by the president (the executive branch). In this example, the legislative branch is “checking” the executive. The U.S. Supreme Court (the judicial branch) can reject a law passed by Congress (the legislative branch). In this example, the judicial branch is “checking” the legislative branch. This separation of powers limits the power of the government and prevents the government from violating the rights of the people."
               },
             @{QuestionNumberKey: @"15",
               QuestionTitleKey: @"Who is in charge of the executive branch?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"The President"],
                             BadAnswerKey: @[@"The Vice President",
                             @"The Speaker of the House",
                             @"The Democratic Majority Leader",
                             @"The Republican Majority Leader",
                             @"The Department of State"],
               ExplanationKey: @"The job of the executive branch is to carry out, or execute, federal laws and enforce laws passed by Congress. The head of the executive branch is the president. The president is both the head of state and the head of government. The president’s powers include the ability to sign treaties with other countries and to select ambassadors to represent the United States around the world. The president also sets national policies and proposes laws to Congress. The president names the top leaders of the federal departments."
               },
             @{QuestionNumberKey: @"16",
               QuestionTitleKey: @"Who makes federal laws?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Congress",
                             @"The Senate and House (of Representatives)",
                             @"US/National legislature"],
                             BadAnswerKey: @[@"The Supreme Court",
                             @"States",
                             @"The FBI",
                             @"The Declaration of Independence",
                             @"The Emancipation Proclamation"],
               ExplanationKey: @"Congress makes federal laws. A federal law usually applies to all states and all people in the United States. Either side of Congress—the Senate or the House of Representatives—can propose a bill to address an issue. When the Senate proposes a bill, it sends the bill to a Senate committee. The Senate committee studies the issue and the bill. When the House of Representatives proposes a bill, it sends the bill to a House of Representatives committee. The committee studies the bill and sometimes makes changes to it. Then the bill goes to the full House or Senate for consideration. When each chamber passes its own version of the bill, it often goes to a “conference committee.” The conference committee has members from both the House and the Senate. This committee discusses the bill, tries to resolve the differences, and writes a report with the final version of the bill. Then the committee sends the final version of the bill back to both houses for approval. If both houses approve the bill, it is considered “enrolled.” An enrolled bill goes to the president to be signed into law. If the president signs the bill, it becomes a federal law."
               },
             @{QuestionNumberKey: @"17", //this is where I stoped changing the answers
               QuestionTitleKey: @"What are the two parts of the U.S. Congress?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"The Senate and House (of Representatives)"],
                             BadAnswerKey: @[@"The Judical and Legislative",
                             @"The Political and Non-political",
                             @"The Political and Military",
                             @"State and Church",
                             @"Senators and Lobbyists"],
               ExplanationKey: @"Congress is divided into two parts—the Senate and the House of Representatives. Because it has two “chambers,” the U.S. Congress is known as a “bicameral” legislature. The system of checks and balances works in Congress. Specific powers are assigned to each of these chambers. For example, only the Senate has the power to reject a treaty signed by the president or a person the president chooses to serve on the Supreme Court. Only the House of Representatives has the power to introduce a bill that requires Americans to pay taxes."
               },
             @{QuestionNumberKey: @"18",
               QuestionTitleKey: @"How many U.S. Senators are there?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"100" ],
                        BadAnswerKey: @[@"52",
                             @"104",
                             @"50",
                             @"435",
                             @"80"],
               ExplanationKey: @"There are 100 senators in Congress, two from each state. All states have equal power in the Senate because each state has the same number of senators. States with a very small population have the same number of senators as states with very large populations. The Framers of the Constitution made sure that the Senate would be small. This would keep it more orderly than the larger House of Representatives."
               },
             @{QuestionNumberKey: @"19",
               QuestionTitleKey: @"We elect a U.S. Senator for how many years?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"6"],
                             BadAnswerKey: @[@"2",
                             @"4",
                             @"8",
                             @"12",
                             @"7"],
               ExplanationKey: @"The Framers of the Constitution wanted senators to be independent from public opinion. They thought a fairly long, six-year term would give them this protection. They also wanted longer Senate terms to balance the shorter two-year terms of the members of the House, who would more closely follow public opinion. The Constitution puts no limit on the number of terms a senator may serve. Elections for U.S. senators take place on even-numbered years. Every two years, one-third of the senators are up for election."
               },
             @{QuestionNumberKey: @"20", //need the Senator info from storage
               QuestionTitleKey: @"Who is one of your state’s U.S. Senators now?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Answer from storage",
                             @"Answer two from storage"],
                             BadAnswerKey: @[@"Joe Biden",
                             @"Hilary Clinton",
                             @"John Kerry",
                             @"Bill Clinton",
                             @"George Bush"],
               ExplanationKey: @"Each State has 2 Senators."
               },
             @{QuestionNumberKey: @"21",
               QuestionTitleKey: @"The House of Representatives has how many voting members?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"435"],
                             BadAnswerKey: @[@"100",
                             @"52",
                             @"535",
                             @"200",
                             @"152"],
               ExplanationKey: @"The House of Representatives is the larger chamber of Congress. Since 1912, the House of Representatives has had 435 voting members. However, the distribution of members among the states has changed over the years. Each state must have at least one representative in the House. Beyond that, the number of representatives from each state depends on the population of the state. The Constitution says that the government will conduct a census of the population every 10 years to count the number of people in each state. The results of the census are used to recalculate the number of representatives each state should have. For example, if one state gains many residents that state could get one or more new representatives. If another state loses residents, that state could lose one or more. But the total number of voting U.S. representatives does not change."
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"We elect a U.S. Representative for how many years?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"2"],
               BadAnswerKey: @[@"4",
                               @"6",
                               @"8",
                               @"12",
                               @"9"],
               ExplanationKey: @"People who live in a representative’s district are called “constituents.” Representatives tend to reflect the views of their constituents. If representatives do not do this, they may be voted out of office. The Framers of the Constitution believed that short two-year terms and frequent elections would keep representatives close to their constituents, public opinion, and more aware of local and community concerns. The Constitution puts no limit on the number of terms a representative may serve. All representatives are up for election every two years."
               },
             @{QuestionNumberKey: @"23",
               QuestionTitleKey: @"Name your U.S. Representative",
               AnswersNeededKey: @1,
               AnswerKey : @[@"answer from storage"],
               BadAnswerKey: @[@"John Kerry",
                               @"Hillary Clinton",
                               @"Bill Clinton",
                               @"Joseph Biden",
                               @"George Bush"],
               ExplanationKey: @"Your representative represents you and your local community and is elected every 2 years."
               },
             @{QuestionNumberKey: @"24",
               QuestionTitleKey: @"Who does a U.S. Senator represent?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"All People of the State"],
               BadAnswerKey: @[@"The National Government",
                               @"Only your local community",
                               @"Only those who voted for them",
                               @"Only the political minorty",
                               @"only those who live close to them"],
               ExplanationKey: @"Senators are elected to serve the people of their state for six years. Each of the two senators represents the entire state. Before the 17th Amendment to the Constitution was ratified in 1913, the state legislatures elected the U.S. senators to represent their state. Now, all the voters in a state elect their two U.S. senators directly."
               },
             @{QuestionNumberKey: @"25",
               QuestionTitleKey: @"Why do some states have more Representatives than other states?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Because of the state's population",
                             @"Because they have more people",
                             @"Because some states have more people"],
               BadAnswerKey: @[@"Because people like those states more",
                               @"Because those states are more popular",
                               @"Because those states have more money",
                               @"Because those states were founded sooner",
                               @"because some states have more land"],
               ExplanationKey: @"The Founding Fathers wanted people in all states to be represented fairly. In the House of Representatives, a state’s population determines the number of representatives it has. In this way, states with many people have a stronger voice in the House. In the Senate, every state has the same number of senators. This means that states with few people still have a strong voice in the national government."
               },
             @{QuestionNumberKey: @"26",
               QuestionTitleKey: @"We elect a President for how many years?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"4"],
               BadAnswerKey: @[@"6",
                               @"2",
                               @"8",
                               @"12",
                               @"6"],
               ExplanationKey: @"Early American leaders thought that the head of the British government, the king, had too much power. Because of this, they limited the powers of the head of the new U.S. government. They decided that the people would elect the president every four years."
               },
             @{QuestionNumberKey: @"27",
               QuestionTitleKey: @"In what month do we vote for President?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"November"],
               BadAnswerKey: @[@"December",
                               @"January",
                               @"April",
                               @"July",
                               @"May"],
               ExplanationKey: @"The Constitution did not set a national election day. In the past, elections for federal office took place on different days in different states. In 1845, Congress passed legislation to designate a single day for all Americans to vote. It made Election Day the Tuesday after the first Monday in November. Congress chose November because the United States was mostly rural. By November, farmers had completed their harvests and were available to vote. Another reason for this date was the weather. People were able to travel because it was not yet winter. They chose Tuesday for Election Day so that voters had a full day after Sunday to travel to the polls."
               },
             @{QuestionNumberKey: @"28",
               QuestionTitleKey: @"What is the name of the President of the United States now?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Barack Hussein Obama II",
                             @"Barack Obama",
                             @"Obama"],
               BadAnswerKey: @[@"Hillary Clinton",
                               @"Joe Biden",
                               @"Joseph Biden",
                               @"John Kerry",
                               @"John Boehner"],
               ExplanationKey: @"Barack Obama is the 44th president of the United States. After winning the presidential election of 2008, he became the first African American president of the United States. He won a second term in 2012. As president, he is the head of the executive branch. As commander in chief, he is also in charge of the military. "
               },
             @{QuestionNumberKey: @"29",
               QuestionTitleKey: @"What is the name of the Vice President of the United States now?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"Joseph R. Biden, Jr.",
                             @"Joe Biden",
                             @"Biden"],
               BadAnswerKey: @[@"Hillary Clinton",
                               @"Barack Obama",
                               @"Obama",
                               @"John Kerry",
                               @"John Boehner"],
               ExplanationKey: @"Joseph (Joe) R. Biden, Jr. is the 47th vice president of the United States. Biden was born November 20, 1942 in Pennsylvania. Later, his family moved to Delaware. He graduated from the University of Delaware in 1965. In 1968, he graduated from law school at Syracuse University in New York. From 1972-2009, Biden served as a U.S. senator for the state of Delaware. As vice president, Biden is president of the U.S. Senate and a top advisor to the president. Vice President Biden is married to Jill Biden."
               },
             @{QuestionNumberKey: @"30",
               QuestionTitleKey: @"If the President can no longer serve, who becomes President?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"the Vice President"],
               BadAnswerKey: @[@"The Secretary of State",
                               @"The Senate majority leader",
                               @"The Speaker of the House",
                               @"The Secretary of Defense",
                               @"The House Majority Leader"],
               ExplanationKey: @"If the president dies, resigns, or cannot work while still in office, the vice president becomes president. For this reason, the qualifications for vice president and president are the same."
               },
             @{QuestionNumberKey: @"31",
               QuestionTitleKey: @"If both the President and the Vice President can no longer serve, who becomes President?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"The Speaker of the House"],
               BadAnswerKey: @[@"The Secretary of State",
                               @"The Senate majority leader",
                               @"The Cheif Justice",
                               @"The Secretary of Defense",
                               @"The House Majority Leader"],
               ExplanationKey: @"If both the president and vice president cannot serve, the next person in line is the speaker of the House of Representatives. This has not always been the procedure. Soon after the country was founded, a law was passed that made the Senate president pro tempore the next in line after the president and vice president. The president pro tempore presides over the Senate when the vice president is not there. Later in U.S. history, the secretary of state was third in line."
               },
             @{QuestionNumberKey: @"32",
               QuestionTitleKey: @"Who is the Commander in Chief of the military?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"The President"],
               BadAnswerKey: @[@"The Secretary of State",
                               @"The Senate majority leader",
                               @"The Cheif Justice",
                               @"The Secretary of Defense",
                               @"The House Majority Leader"],
               ExplanationKey: @"The Founding Fathers strongly believed in republican ideals. A republic is a government where a country’s political power comes from the citizens, not the rulers, and is put into use by representatives elected by the citizens. That is why they made the president the commander in chief. They wanted a civilian selected by the people. They did not want a professional military leader. The president commands the armed forces, but Congress has the power to pay for the armed forces and declare war."
               },
             @{QuestionNumberKey: @"33",
               QuestionTitleKey: @"Who signs bills to become laws?",
               AnswersNeededKey: @1,
               AnswerKey : @[@"The President"],
               BadAnswerKey: @[@"The Secretary of State",
                               @"The Senate majority leader",
                               @"The Cheif Justice",
                               @"The Secretary of Defense",
                               @"The House Majority Leader"],
               ExplanationKey: @"Every law begins as a proposal made by a member of Congress, either a senator (member of the Senate) or representative (member of the House of Representatives). When the Senate or House begins to debate the proposal, it is called a “bill.” After debate in both houses of Congress, if a majority of both the Senate and House vote to pass the bill, it goes to the president. If the president wants the bill to become law, he signs it. If the president does not want the bill to become law, he vetoes it. The president cannot introduce a bill. If he has an idea for a bill, he must ask a member of Congress to introduce it."
               },
             @{QuestionNumberKey: @"34",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@"",
                             @""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
               QuestionTitleKey: @"",
               AnswersNeededKey: @1,
               AnswerKey : @[@""],
               BadAnswerKey: @[@"",
                               @"",
                               @"",
                               @"",
                               @""],
               ExplanationKey: @""
               },
             @{QuestionNumberKey: @"22",
                   QuestionTitleKey: @"",
                   AnswersNeededKey: @1,
                   AnswerKey : @[@""],
                   BadAnswerKey: @[@"",
                                   @"",
                                   @"",
                                   @"",
                                   @""],
                   ExplanationKey: @""
                   },
             
             ];
}




@end
